version: "3.13"

services:
  web:
    build:
      context: .
    container_name: todoapp
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=django_db
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_HOST=db
    depends_on:
      - db
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: django
  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6379:6379"  
    command: ["redis-server", "--appendonly", "yes"] 

volumes:
  postgres_data:
